name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: echo "Hello World!"
  printDate:
    runs-on: ubuntu-20.04
    steps: 
      - name: print Date
        run: $date=$(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

          